### ISSUE TITLE
any demos using this package?

### ISSUE THREAD

**Issue by flyingdorothia** [tsumpf/arrShow#12]
Thanks for the package.
I wonder if there is any demo. Where I should start using this code?
Thanks you.

**Comment by siatjiasen** [comment]
Please refer to : https://cds.ismrm.org/protected/13MProceedings/PDFfiles/3719.PDF
https://www.ismrm.org/13/ep07.htm also provide a good presentation on arrayshow.

**Comment by tsumpf** [comment]
Sorry, this tool was a byproduct of a PhD Thesis and I believe, nobody ever wrote a real documentation for this tool.
However, there was a Talk at the ISMRM in 2013, mentioned above by siatjiasen.
I just uploaded the powerpoint to the GitHub Wiki, in case you're not with the ISMRM community.
The source code of the tool also includes the [README.m](https://github.com/tsumpf/arrShow#readme) file, which contains all commands needed for a first start of the tool.
Unfortunately, I don't have a Matlab liscence anymore to test, if this still works in 2022.
